### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [Lukeghenco/first-firehose-app#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by Lukeghenco** [comment]
I had to mess with a couple of different meta tags to get the right performance on my iPad and iPhone 5s. 
This is the meta tag I used on my last commit, and it seems to be working.
I will continue updating my first app to make it look better. 
Thanks
<meta name="viewport" content="initial-scale=1, maximum-scale=1">

**Comment by kenmazaika** [comment]
Solid work, Luke!  The code looks awesome.  :+1:
